use std::fs;
use std::path::Path;

use colored::Colorize;
use openapi_forge::Spec;
use terraform_forge::{
    ProviderSpec, ResourceSpec, generate_provider, generate_resource, generate_test,
};

pub fn run(
    spec_path: &Path,
    resources_dir: &Path,
    output_dir: &Path,
    provider_path: Option<&Path>,
) -> Result<(), Box<dyn std::error::Error>> {
    println!(
        "{} Loading OpenAPI spec from {}",
        "=>".blue().bold(),
        spec_path.display()
    );
    let api = Spec::load(spec_path)?;

    let provider = if let Some(p) = provider_path {
        ProviderSpec::load(p)?
    } else {
        let provider_toml = resources_dir
            .parent()
            .unwrap_or(resources_dir)
            .join("provider.toml");
        if provider_toml.exists() {
            ProviderSpec::load(&provider_toml)?
        } else {
            return Err("No provider.toml found. Use --provider to specify one.".into());
        }
    };

    let defaults = provider.defaults.clone();

    let resource_files = find_toml_files(resources_dir)?;
    println!(
        "{} Found {} resource specs",
        "=>".blue().bold(),
        resource_files.len()
    );

    let resources_out = output_dir.join("resources");
    let provider_out = output_dir.join("provider");
    let tests_out = output_dir.join("resources");
    fs::create_dir_all(&resources_out)?;
    fs::create_dir_all(&provider_out)?;

    let mut type_names = Vec::new();
    let mut tf_names = Vec::new();
    let mut test_count = 0;

    for file in &resource_files {
        let resource = ResourceSpec::load(file)?;

        if let Err(e) = resource.validate(&api) {
            eprintln!("{} {}: {e}", "warning:".yellow().bold(), file.display());
            continue;
        }

        println!("  {} Generating {}", "->".green(), resource.resource.name);

        let generated =
            generate_resource(&resource, &api, &defaults, &provider.provider.sdk_import)?;

        type_names.push(generated.resource_type_name.clone());
        tf_names.push(resource.resource.name.clone());

        // Check for override file
        let override_path = output_dir.join("overrides").join(&generated.file_name);
        if override_path.exists() {
            println!(
                "  {} Override exists, skipping: {}",
                "!!".yellow(),
                generated.file_name
            );
            fs::copy(&override_path, resources_out.join(&generated.file_name))?;
        } else {
            fs::write(resources_out.join(&generated.file_name), &generated.go_code)?;
        }

        // Generate acceptance test scaffold
        let test = generate_test(&resource);
        fs::write(tests_out.join(&test.file_name), &test.go_code)?;
        test_count += 1;
    }

    // Generate provider.go
    println!(
        "  {} Generating provider.go ({} resources)",
        "->".green(),
        type_names.len()
    );
    let data_source_names: Vec<String> = Vec::new();
    let provider_code = generate_provider(&provider, &type_names, &tf_names, &data_source_names);
    fs::write(provider_out.join("provider.go"), &provider_code)?;

    // Generate common helpers
    let helpers = generate_helpers();
    fs::write(resources_out.join("helpers.go"), &helpers)?;

    println!(
        "\n{} Generated {} resources + {} tests + provider.go in {}",
        "done".green().bold(),
        type_names.len(),
        test_count,
        output_dir.display()
    );

    Ok(())
}

fn find_toml_files(dir: &Path) -> Result<Vec<std::path::PathBuf>, Box<dyn std::error::Error>> {
    let mut files = Vec::new();
    if dir.is_dir() {
        for entry in glob::glob(&format!("{}/**/*.toml", dir.display()))? {
            files.push(entry?);
        }
    }
    files.sort();
    Ok(files)
}

fn generate_helpers() -> String {
    r#"// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AkeylessClient wraps the API client with auth.
type AkeylessClient struct {
	GatewayURL string
	Token      string
	HTTPClient *http.Client
}

// NewAkeylessClient creates a new API client.
func NewAkeylessClient(gatewayURL, token string) *AkeylessClient {
	return &AkeylessClient{
		GatewayURL: gatewayURL,
		Token:      token,
		HTTPClient: &http.Client{},
	}
}

// CallEndpoint makes an API POST request to the given endpoint with a map body.
func (c *AkeylessClient) CallEndpoint(ctx context.Context, endpoint string, params map[string]interface{}) (map[string]interface{}, error) {
	if c.Token != "" {
		params["token"] = c.Token
	}

	jsonBody, err := json.Marshal(params)
	if err != nil {
		return nil, fmt.Errorf("marshaling request: %w", err)
	}

	url := fmt.Sprintf("%s%s", c.GatewayURL, endpoint)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(jsonBody))
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("making request to %s: %w", endpoint, err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("reading response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("API error %d on %s: %s", resp.StatusCode, endpoint, string(respBody))
	}

	var result map[string]interface{}
	if len(respBody) > 0 {
		if err := json.Unmarshal(respBody, &result); err != nil {
			return nil, fmt.Errorf("decoding response from %s: %w", endpoint, err)
		}
	}

	return result, nil
}

// expandStringSet converts a TF Set to a Go string slice.
func expandStringSet(ctx context.Context, set types.Set) []string {
	if set.IsNull() || set.IsUnknown() {
		return nil
	}
	var result []string
	set.ElementsAs(ctx, &result, false)
	return result
}

// GetNestedString retrieves a string from a nested map using dot-notation path.
func GetNestedString(data map[string]interface{}, path string) (string, bool) {
	parts := strings.Split(path, ".")
	current := data

	for i, part := range parts {
		if i == len(parts)-1 {
			if v, ok := current[part]; ok {
				switch val := v.(type) {
				case string:
					return val, true
				case float64:
					return fmt.Sprintf("%v", val), true
				case bool:
					return fmt.Sprintf("%v", val), true
				default:
					return fmt.Sprintf("%v", val), true
				}
			}
			return "", false
		}

		if next, ok := current[part]; ok {
			if m, ok := next.(map[string]interface{}); ok {
				current = m
			} else {
				return "", false
			}
		} else {
			return "", false
		}
	}

	return "", false
}

// GetNestedStringSlice retrieves a string slice from a nested map.
func GetNestedStringSlice(data map[string]interface{}, path string) ([]string, bool) {
	parts := strings.Split(path, ".")
	current := data

	for i, part := range parts {
		if i == len(parts)-1 {
			if v, ok := current[part]; ok {
				if arr, ok := v.([]interface{}); ok {
					result := make([]string, 0, len(arr))
					for _, item := range arr {
						if s, ok := item.(string); ok {
							result = append(result, s)
						}
					}
					return result, true
				}
			}
			return nil, false
		}

		if next, ok := current[part]; ok {
			if m, ok := next.(map[string]interface{}); ok {
				current = m
			} else {
				return nil, false
			}
		} else {
			return nil, false
		}
	}

	return nil, false
}
"#
    .to_string()
}
