use std::fs;
use std::path::Path;

use colored::Colorize;
use openapi_forge::Spec;
use terraform_forge::{ProviderSpec, ResourceSpec, generate_provider, generate_resource};

pub fn run(
    spec_path: &Path,
    resources_dir: &Path,
    output_dir: &Path,
    provider_path: Option<&Path>,
) -> Result<(), Box<dyn std::error::Error>> {
    println!(
        "{} Loading OpenAPI spec from {}",
        "=>".blue().bold(),
        spec_path.display()
    );
    let api = Spec::load(spec_path)?;

    let provider = if let Some(p) = provider_path {
        ProviderSpec::load(p)?
    } else {
        // Look for provider.toml in resources dir parent
        let provider_toml = resources_dir
            .parent()
            .unwrap_or(resources_dir)
            .join("provider.toml");
        if provider_toml.exists() {
            ProviderSpec::load(&provider_toml)?
        } else {
            return Err("No provider.toml found. Use --provider to specify one.".into());
        }
    };

    let defaults = provider.defaults.clone();

    // Find all resource TOML files
    let resource_files = find_toml_files(resources_dir)?;
    println!(
        "{} Found {} resource specs",
        "=>".blue().bold(),
        resource_files.len()
    );

    // Create output directories
    let resources_out = output_dir.join("resources");
    let provider_out = output_dir.join("provider");
    fs::create_dir_all(&resources_out)?;
    fs::create_dir_all(&provider_out)?;

    let mut type_names = Vec::new();
    let mut tf_names = Vec::new();

    for file in &resource_files {
        let resource = ResourceSpec::load(file)?;

        // Validate against spec
        if let Err(e) = resource.validate(&api) {
            eprintln!("{} {}: {e}", "warning:".yellow().bold(), file.display());
            continue;
        }

        println!("  {} Generating {}", "->".green(), resource.resource.name);

        let generated =
            generate_resource(&resource, &api, &defaults, &provider.provider.sdk_import)?;

        type_names.push(generated.resource_type_name.clone());
        tf_names.push(resource.resource.name.clone());

        // Check for override file
        let override_path = output_dir.join("overrides").join(&generated.file_name);
        if override_path.exists() {
            println!(
                "  {} Override exists, skipping: {}",
                "!!".yellow(),
                generated.file_name
            );
            // Copy override to resources output
            fs::copy(&override_path, resources_out.join(&generated.file_name))?;
        } else {
            fs::write(resources_out.join(&generated.file_name), &generated.go_code)?;
        }
    }

    // Generate provider.go
    println!(
        "  {} Generating provider.go ({} resources)",
        "->".green(),
        type_names.len()
    );
    let provider_code = generate_provider(&provider, &type_names, &tf_names);
    fs::write(provider_out.join("provider.go"), &provider_code)?;

    // Generate common helpers
    let helpers = generate_helpers();
    fs::write(resources_out.join("helpers.go"), &helpers)?;

    println!(
        "\n{} Generated {} resources + provider.go in {}",
        "done".green().bold(),
        type_names.len(),
        output_dir.display()
    );

    Ok(())
}

fn find_toml_files(dir: &Path) -> Result<Vec<std::path::PathBuf>, Box<dyn std::error::Error>> {
    let mut files = Vec::new();
    if dir.is_dir() {
        for entry in glob::glob(&format!("{}/**/*.toml", dir.display()))? {
            files.push(entry?);
        }
    }
    files.sort();
    Ok(files)
}

fn generate_helpers() -> String {
    r#"// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"bytes"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AkeylessClient wraps the API client with auth.
type AkeylessClient struct {
	GatewayURL string
	Token      string
	HTTPClient *http.Client
}

// NewAkeylessClient creates a new API client.
func NewAkeylessClient(gatewayURL, token string) *AkeylessClient {
	return &AkeylessClient{
		GatewayURL: gatewayURL,
		Token:      token,
		HTTPClient: &http.Client{},
	}
}

// Call makes an API request to the given endpoint.
func (c *AkeylessClient) Call(ctx context.Context, body interface{}) (json.RawMessage, error) {
	payload, ok := body.(interface{ Endpoint() string })
	if !ok {
		return nil, fmt.Errorf("body must implement Endpoint()")
	}

	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshaling request: %w", err)
	}

	url := fmt.Sprintf("%s%s", c.GatewayURL, payload.Endpoint())
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(jsonBody))
	if err != nil {
		return nil, fmt.Errorf("creating request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("making request: %w", err)
	}
	defer resp.Body.Close()

	var result json.RawMessage
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decoding response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("API error %d: %s", resp.StatusCode, string(result))
	}

	return result, nil
}

// expandStringSet converts a TF Set to a Go string slice.
func expandStringSet(ctx context.Context, set types.Set) []string {
	if set.IsNull() || set.IsUnknown() {
		return nil
	}
	var result []string
	set.ElementsAs(ctx, &result, false)
	return result
}
"#
    .to_string()
}
